version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:jessie

    working_directory: /src/docker-elasticsearch-circleci

    environment:
      CONTAINER_NAME: es_container
      DOCKER_VERSION: "17.03.0-ce"
      IMAGE_TAG_TEST: kenju/elasticsearch-circleci:test

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            # TODO:
            # - docker-{{ .Environment.DOCKER_VERSION }}
            - docker-17.03.0-ce
            - docker-

      - run:
          name: Install Docker client
          command: |
            if [[ ! -x /usr/bin/docker || $(docker version --format '{{ .Client.Version }}') != "${DOCKER_VERSION}" ]]; then
              set -x
              curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
              tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
              ls -la /tmp/docker/
              ls -la /tmp/docker/*
              mv /tmp/docker/* /usr/bin
            fi

      - save_cache:
          # TODO:
          # key: docker-{{ .Environment.DOCKER_VERSION }}
          key: docker-17.03.0-ce
          paths:
            - /usr/bin/docker

      - run:
          name: Build a docker image from Dockerfile
          command: docker build -t $IMAGE_TAG_TEST image/

      - run:
          name: Run a container from the image
          command: |
            # run docker for development use
            #   https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode
            # here is why to set 'http.host' and 'transport.host'
            #   https://www.elastic.co/guide/en/elasticsearch/reference/5.3/bootstrap-checks.html#_development_vs_production_mode
            docker run -d \
                       -p 9200:9200 \
                       --name $CONTAINER_NAME \
                       -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" \
                       $IMAGE_TAG_TEST

      - run: docker ps

      - run:
          name: Health Check Elasticsearch from primary_container
          environment:
            HEALTH_CHECK_RETRY_LIMIT: 20
            HEALTH_CHECK_RETRY_DELAY: 3
            HEALTH_CHECK_PORT: 9200
          command: |
            docker run --network container:$CONTAINER_NAME \
              appropriate/curl --silent \
                               --retry $HEALTH_CHECK_RETRY_LIMIT \
                               --retry-delay $HEALTH_CHECK_RETRY_DELAY \
                               --retry-connrefused http://localhost:$HEALTH_CHECK_PORT

      - deploy:
          name: Publish to Docker Hub
          environment:
            BASE_TAG: kenju/elasticsearch-circleci
          command: |
            TIMESTAMP=`date "+%Y%m%d%H%M"`
            IMAGE_TAG_DEPLOY="$BASE_TAG:$TIMESTAMP"
            LATEST_TAG="$BASE_TAG:latest"

            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

            docker build -t $IMAGE_TAG_DEPLOY image/
            docker push $IMAGE_TAG_DEPLOY

            docker build -t $LATEST_TAG image/
            docker push $LATEST_TAG

            git tag $TIMESTAMP
            git push --tags
